FROM node:20-alpine
RUN npm install -g pnpm nodemon ts-node
WORKDIR /app
ENV NODE_PATH=/app/node_modules
CMD sh -c "pnpm install --prefer-offline && nodemon --watch src --ext ts --exec 'ts-node --transpile-only' src/index.ts"
